name: autograding
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - uses: iterative/setup-cml@v1

      - name: Debug Git Status
        run: |
          git status
          git remote -v

      - name: autograde_task
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python eval.py >> report.md
          cml-send-comment report.md