name: autograding
on:
  - push
  - workflow_dispatch
permissions:
  checks: write
  contents: write
  actions: write
jobs:
  run:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
  
      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup CML Report
        uses: iterative/setup-cml@v2

      - name: autograde_task
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python eval.py >> report.md
          cml comment create report.md --repo https://github.com/fuisl/assignment1 --token $repo_token

  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Python test
        id: python-test
        uses: education/autograding-python-grader@v1
      - name: Python test with score
        id: python-test-with-score
        uses: education/autograding-python-grader@v1
        with:
          max-score: 30
      - name: Autograding Reporter
        uses: ./
        env:
          PYTHON-TEST_RESULTS: "${{steps.python-test.outputs.result}}"
          PYTHON-TEST-WITH-SCORE_RESULTS: "${{steps.python-test-with-score.outputs.result}}"
        with:
          runners: shout-test,a-command-test,python-test,python-test-with-score
